FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY frontend/ /app/frontend/

EXPOSE 8503

CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.port=8503", "--server.address=0.0.0.0"]