services:
  backend:
    # build: ./backend
    image: arpan794/churn-backend:v1
    ports:
      - "8000:8000"
    restart: always

  frontend:
    # build: ./frontend
    image: arpan794/churn-frontend:v1
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/predict
    depends_on:
      - backend
    restart: always