services:

  backend:
    build: ./backend
    ports:
      - "8002:8002"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8503:8503"
    environment:
      - API_URL=http://backend:8002/translate
    depends_on:
      - backend
    restart: always